# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 669debed0849dc25d6e0857df30110312f5667fdab7fb788fa2acf9a3a1443fea555a8f3b1ecf91eb3c0faf2ed7bc1f3452d99f84377201127e106d319c4b795

test:
  secret_key_base: 8b0c4890931c6d43b62151c0a04066d0bb7ba2bd8cfee0d4907db1ff15c44ca0ccdbfcf857ad470615ab697bb00ff62fe54e124518cff0969c77431882ff70d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
